language: C
sudo: false

branches:
  only:
    - master
    - travis

addons:
  apt:
    packages:
      - cabal-install-2.0
      - ghc-8.2.2
    sources:
      - hvr-ghc

cache:
  directories:
    - $HOME/.cabal/
    - $HOME/.ghc/

install:
  - export PATH=$HOME/.cabal/bin:/opt/ghc/8.2.2/bin:/opt/cabal/2.0/bin:$PATH
  - cabal update
  - sed -i 's/^jobs:/-- jobs:/' $HOME/.cabal/config
  - cabal install -f FFI -f LLVM -f GMP idris

script:
  - cd ..
  - idris --mkdoc TParsec.ipkg 
  - mv tparsec_doc/* .

after_success:
  # uploading to gh-pages
  - git init
  - git config --global user.name "Travis CI bot"
  - git config --global user.email "travis-ci-bot@travis.fake"
  - git remote add upstream https://$GH_TOKEN@github.com/gallais/idris-tparsec.git &>/dev/null
  - git fetch upstream && git reset upstream/gh-pages
  - git add -f \*.html \*.css
  - git commit -m "Automatic HTML update via Travis"
  - git push -q upstream HEAD:gh-pages &>/dev/null;
